-- woven.lua — generated by setup guide
-- Edit this file to customize woven behavior.

woven.theme({
    background    = "#282828",
    border        = "#d79921",
    text          = "#ebdbb2",
    accent        = "#458588",
    border_radius = 12,
    font          = "JetBrainsMono Nerd Font",
    font_size     = 13,
    opacity       = 0.92,
    blur          = true,
})

woven.settings({
    toggle_key  = "SUPER+TAB",
    animation   = "slide",
    scroll_dir  = "horizontal",
})

woven.workspaces({
    show_empty = false,
    popout     = true,
    popout_metrics = { "cpu", "memory" },
    popout_side    = "right",
})

-- Add your hooks here:
-- woven.on("workspace_focus", function(ws)
--     woven.log.info("Focused workspace " .. ws.id)
-- end)

-- Add your window controls here:
-- woven.bind("fullscreen", function(win) woven.window.fullscreen(win.id) end)
-- woven.bind("close",      function(win) woven.window.close(win.id) end)
-- woven.bind("focus",      function(win) woven.window.focus(win.id) end)
