-- Sane defaults used when building config from scratch
local M = {}
M.values = {
    toggle_key      = "SUPER+TAB",
    animation       = "slide",
    scroll_dir      = "horizontal",
    overlay_opacity = 0.92,
    blur            = true,
    show_empty_ws   = false,
    popout          = true,
    background      = "#1e1e2e",
    border          = "#cba6f7",
    text            = "#cdd6f4",
    accent          = "#89b4fa",
    border_radius   = 12,
    font            = "JetBrainsMono Nerd Font",
    font_size       = 13,
}

-- Render the values table into a woven.lua config string
function M.render(values)
    local v = values or M.values
    return string.format([[
-- woven.lua — generated by setup guide
-- Edit this file to customize woven behavior.

woven.theme({
    background    = %q,
    border        = %q,
    text          = %q,
    accent        = %q,
    border_radius = %d,
    font          = %q,
    font_size     = %d,
    opacity       = %.2f,
    blur          = %s,
})

woven.settings({
    toggle_key  = %q,
    animation   = %q,
    scroll_dir  = %q,
})

woven.workspaces({
    show_empty = %s,
    popout     = %s,
    popout_metrics = { "cpu", "memory" },
    popout_side    = "right",
})

-- Add your hooks here:
-- woven.on("workspace_focus", function(ws)
--     woven.log.info("Focused workspace " .. ws.id)
-- end)

-- Add your window controls here:
-- woven.bind("fullscreen", function(win) woven.window.fullscreen(win.id) end)
-- woven.bind("close",      function(win) woven.window.close(win.id) end)
-- woven.bind("focus",      function(win) woven.window.focus(win.id) end)
]],
        v.background, v.border, v.text, v.accent,
        v.border_radius, v.font, v.font_size, v.overlay_opacity,
        tostring(v.blur),
        v.toggle_key, v.animation, v.scroll_dir,
        tostring(v.show_empty_ws), tostring(v.popout)
    )
end

return M
